# 서울시 범죄현황 데이터를 통한 CCTV 설치 필요지역 파악하기

## 1. 서울시 자치구별 범죄현황 데이터 읽어오기

In [15]:
import pandas as pd

# Colab에서는 파일의경로명을 해당 파일에서 점 세개 버튼의 경로 복사로 복사해 사용
#예) Crime_Seoul = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/AI_2주차_실습파일_오프라인/서울시 5대 범죄 발생 현황 통계.txt'.......)

# 강의자료 2, 6쪽 참조, 여기서 불러오로 파일은 encodind = 'utf-8' 또는 생략해도 됨
#('./서울시 5대 범죄 발생 현황 통계.txt', sep= '\t', encoding= 'utf-8')
Crime_Seoul = pd.read_csv('./서울시 5대 범죄 발생 현황 통계.txt',sep='\t',encoding='utf-8');
Crime_Seoul

,기간,자치구,합계,합계.1,살인,살인.1,강도,강도.1,강간강제추행,강간강제추행.1,절도,절도.1,폭력,폭력.1
0,기간,자치구,발생,검거,발생,검거,발생,검거,발생,검거,발생,검거,발생,검거
1,2019,합계,103668,74805,136,128,136,133,6469,6007,42204,21284,54723,47253
2,2019,종로구,3846,4117,4,5,7,8,238,1143,1515,1069,2082,1892
3,2019,중구,4327,2804,2,1,6,5,195,115,2202,1050,1922,1633
4,2019,용산구,3313,2611,3,3,3,4,272,237,999,544,2036,1823
5,2019,성동구,2512,1838,6,5,9,10,133,96,970,511,1394,1216
6,2019,광진구,4011,2816,4,5,6,5,273,213,1875,1008,1853,1585
7,2019,동대문구,3692,2818,6,6,10,9,168,143,1531,827,1977,1833
8,2019,중랑구,4268,3138,10,10,4,5,138,108,1666,908,2450,2107
9,2019,성북구,2877,2323,3,3,3,3,176,130,1082,731,1613,1456
10,2019,강북구,3838,3023,6,6,3,2,176,145,1229,664,2424,2206
11,2019,도봉구,2110,1497,1,1,5,5,90,83,790,394,1224,1014
12,2019,노원구,4153,2964,4,4,3,3,184,158,1498,681,2464,2118
13,2019,은평구,3880,3000,3,3,1,1,194,162,1565,977,2117,1857
14,2019,서대문구,2943,2020,2,1,5,5,175,154,1226,600,1535,1260
15,2019,마포구,4842,3170,2,2,2,2,495,417,2190,917,2153,1832
16,2019,양천구,3214,2124,6,6,2,2,127,112,1477,634,1602,1370
17,2019,강서구,4924,3543,8,9,3,4,306,257,2050,1077,2557,2196
18,2019,구로구,4707,3291,10,9,3,4,226,165,1916,965,2552,2148
19,2019,금천구,3105,2343,6,6,10,6,153,126,1157,615,1779,1590
20,2019,영등포구,5820,3787,10,10,3,3,356,239,2409,1068,3042,2467
21,2019,동작구,3400,2195,4,2,1,1,251,110,1328,579,1816,1503
22,2019,관악구,5328,3810,13,10,10,11,408,335,2223,1085,2674,2369
23,2019,서초구,5542,3750,5,5,7,5,616,412,2270,1118,2644,2210
24,2019,강남구,7304,5069,5,3,5,6,666,562,2970,1339,3658,3159
25,2019,송파구,5698,3799,7,8,10,10,273,230,2416,1016,2992,2535
26,2019,강동구,4014,2955,6,5,15,14,180,155,1650,907,2163,1874

## 2. 데이터 살펴보기

### 2-1. 행x열 수, 열이름, 인덱스를 살펴보자

In [ ]:
print(Crime_Seoul.shape)
print(Crime_Seoul.index)
print(Crime_Seoul.columns)

### 2-2. 데이터의 상위 5행과 하위 5행을 살펴보자

In [10]:
Crime_Seoul.head()

,구분,총계,2011년 이전,2011년,2012년,2013년,2014년,2015년,2016년,2017년,2018년,2019년,2020년
0,계,75431,5901,1619,2228,0,4368,6742,8300,10100,9687,11657,10232
1,종로구,1729,216,7,10,582,210,150,1,259,85,9,200
2,중구,2001,16,6,199,90,125,218,333,462,228,194,130
3,용산구,2383,31,3,71,234,125,221,298,351,125,307,617
4,성동구,3515,487,26,122,207,112,335,309,790,409,262,456

In [12]:
Crime_Seoul.tail()

,구분,총계,2011년 이전,2011년,2012년,2013년,2014년,2015년,2016년,2017년,2018년,2019년,2020년
21,관악구,4909,320,120,84,431,441,608,620,684,674,596,331
22,서초구,3730,0,117,72,93,71,563,516,1061,436,361,440
23,강남구,6645,62,61,72,368,455,845,1307,1004,744,796,931
24,송파구,2743,64,9,61,86,85,215,146,241,542,1068,226
25,강동구,2547,223,45,27,227,49,154,202,273,377,356,614

### 2-3. 데이터의 타입, 아이템수, 누락데이터 수 등을 살펴보자

In [ ]:
Crime_Seoul

## 3. CCTV 데이터 정리하기

### 3.1 데이터의 컬럼 이름을 변경해보자

In [ ]:
#데이터의 열이름 변경:
#'자치구' -> '구별',
#'합계' -> '발생합계', '합계.1' -> '검거합계',
#'살인.1'-> '살인검거',
#'강도.1' -> '강도검거',
#'강간강제추행.1' -> '강간강제추행검거',
#'절도.1' -> '절도검거',
#'폭력.1' -> '폭력검거'

### 3.2 불필요한 행과 열을 삭제하자

In [ ]:
#'기간'열 삭제 (columns='기간', axis=1, inplace=True)

In [ ]:
#0,1행 삭제 (index=[0,1], axis=0, inplace=True)

In [ ]:
#기존 인덱스를 버리고 인덱스 0부터 다시 설정 (drop=True, inplace=True)

## 4. 범죄현황 데이터 자세히 보기

### 4-1. 범죄발생이 가장 많은/적은 상위 5개 구는 어디일까?

In [ ]:
#'범죄발생'이 가장 많은 구, 데이터 '발생합계'열을 기준으로 내림차순 정렬하기

In [ ]:
#범죄발생이 가장 적은 구, 데이터 '발생합계'열을 기준으로 오름차순 정렬하기

### 4-2 각 범죄별 검거율을 계산하여 검거율 열을 추가하자

In [ ]:
# 각 컬럼의 데이터 타입을 확인
# 검거율을 계산하기 위해서는 데이터가 정수형이거나 실수형이여야 함
# 이 정수형이 아니라 문자열 형임을 알수 있다. 문자열 형은 수학연산이 불가
Crime_Seoul.info()

In [ ]:
#각 열의 문자열 형의 데이터를 정수형으로 변경
Crime_Seoul = Crime_Seoul.astype({'발생합계':'int64', '검거합계':'int64',
                                  '살인':'int64', '살인검거':'int64',
                                  '강도':'int64', '강도검거':'int64',
                                  '강간강제추행':'int64', '강간강제추행검거':'int64',
                                  '절도':'int64', '절도검거':'int64',
                                  '폭력':'int64', '폭력검거':'int64'})
Crime_Seoul.head()

In [ ]:
# 각 컬럼의 데이터 타입이 정수형으로 변경되었음 확인

Crime_Seoul.info()

In [ ]:
#검거 수/발생 수 * 100
#예시) Crime_Seoul['검거율'] = Crime_Seoul['검거합계']/ Crime_Seoul['발생합계']  * 100
#예시) Crime_Seoul['살인검거율'] = Crime_Seoul['살인검거']/ Crime_Seoul['살인']  * 100

Crime_Seoul['검거율'] = 
Crime_Seoul['살인검거율'] = 
Crime_Seoul['강도검거율'] = 
Crime_Seoul['강간강제추행검거율'] = 
Crime_Seoul['절도검거율'] = 
Crime_Seoul['폭력검거율'] = 
                    
Crime_Seoul.head()

### 4-3. 각 범죄의 검거수를 삭제하자.

In [ ]:
#각 범죄의 검거 열은 삭제, 검거수는 검거율로 대체해 사용 
#(columns=['살인검거','강도검거','강간강제추행검거','절도검거', '폭력검거'], axis=1, inplace=True)

### 4-4. 범죄의 검거율이 가장 높은/낮은 상위 5개구는 어디일까?

In [ ]:
#범죄 검거율이 가장 높은 구, 데이터 '검거율'열을 기준으로 정렬하기

In [ ]:
#범죄 검거율이 가장 낮은 구, 데이터 '검거율'열을 기준으로 정렬하기

## 5. 인구수와 CCTV수 데이터와 범죄 현황 데이터 합치기

### 5-1 인구수와 CCTV 수 데이터 가져오기

In [ ]:
# 서울시 자치구별 CCTV 현황 분석에서 정리하여 저장했던 'CCTV_pop.xlsx' 액셀 파일 열기

CCTV_pop = pd.read_excel('./CCTV_pop.xlsx')
CCTV_pop.head()

In [ ]:
# CCTV_pop 데이터에서 '총계','인구수' 열만 가져와서 추가하기 
Crime_Seoul['CCTV수']=CCTV_pop['총계']
Crime_Seoul['인구수']=CCTV_pop['인구수']
Crime_Seoul.head()

In [ ]:
#구별로 인덱스 설정
Crime_Seoul.set_index('구별', inplace=True)
Crime_Seoul.head()

## 5. 범죄 데이터 시각화 하기

In [ ]:
#한글 폰트 깨짐 방지 코드
import matplotlib.pyplot as plt
import seaborn as sns

import platform
path = "c:/windows/Fonts/malgun.ttf"
from matplotlib import font_manager, rc

if platform.system() == 'Darwin':
    rc('font', family='AppleGothic')
elif platform.system() == 'Windows':
    font_name = font_manager.FontProperties(fname=path).get_name()
    rc('font', family=font_name)
else :
    print('Unknown system... sorry~~~')

### 5.1 범죄 발생수가 가장 많은 구는 어디인가?

In [ ]:
#막대 그래프 그리기
# '발생합계로 소팅하여 막대 그래프 그리기

### 5.2 범죄 검거율이 가장 높은 구는 어디인가?

In [ ]:
#막대 그래프 그리기
# '검거율'로 소팅하여 막대 그래프 그리기

### 5.3 CCTV수가 가장 많은 구는 어디일까?

In [ ]:
#막대 그래프 그리기
# 'CCTV수'로 소팅하여 막대 그래프 그리기

### 5.4 강도, 살인, 폭력은 어떤 관계에 있을까?

In [ ]:
#강도, 살인, 폭력에 대한 상간관계 그래프 
#pairplot은 그리도(grid) 형태로 각 집합의 조합에 대해 히스토그램 또는 분포도를 그려주는 함수
sns.pairplot(Crime_Seoul, vars=['강도','살인','폭력'], kind='reg', height=3) #kind='reg'는 차트 종류를 산점도라는 의미
plt.show()

### 5.5 살인, 강도와 인구수와 CCTV수와 어떤 관계에 있을까?

In [ ]:
#살인, 강도, 인구수, CCTV수에 대한 상간관계 그래프 
#pairplot은 그리도(grid) 형태로 각 집합의 조합에 대해 히스토그램 또는 분포도를 그려주는 함수
sns.pairplot(Crime_Seoul, x_vars=['인구수','CCTV수'], y_vars=['살인','강도'], kind='reg', height=3) #kind='reg'는 차트 종류를 산점도라는 의미
plt.show()

### 5.6 인구수와 CCTV수는 살인검거율과 폭력검거율과 어떤 관계에 있을까?

In [ ]:
#살인, 강도, 인구수, CCTV수에 대한 상간관계 그래프 
#pairplot은 그리도(grid) 형태로 각 집합의 조합에 대해 히스토그램 또는 분포도를 그려주는 함수
sns.pairplot(Crime_Seoul, x_vars=['인구수','CCTV수'], y_vars=['살인검거율','폭력검거율'], kind='reg', height=3) #kind='reg'는 차트 종류를 산점도라는 의미
plt.show()

In [ ]:
Crime_Seoul.head()

In [ ]:
#범죄발생수, 검거율, CCTV수, 인구수 항목만 따로 가져오기 
df = Crime_Seoul[['발생합계','검거율','CCTV수','인구수']]
df.head()
#항목별 상관관계 살펴보기, 대각선을 중심으로 대칭, 음수는 두 데이터가 음의 상관관게, 양수는 양의 상간관계,
#절대값이 1에 가까울 수록 상관도가 높음
df.corr()

In [ ]:
#상관관계 그래프로 보기, 양의 상관관계는 녹색계열, 음의 상관관계는 보라색 계열
plt.matshow(df.corr())

## 6. 위의 분석 결과를 보고 CCTV수가 범죄발생 및 검거에 미치는 영향과 CCTV 설치에 대한 자신의 생각을 아래에 정리해 보자

### 나의생각 :